name = "semantic_versioning"
version = "2.0-dev"
description = "Semantic Versioning in Ada"
licenses = "LGPL-3.0-only"

authors = [ "Alejandro R. Mosteo" ]
maintainers = [ "alejandro@mosteo.com", ]
maintainers-logins = [ "mosteo", ]

tags = ["semver", "semantic", "versioning"]
