name = "semantic_versioning"
version = "2.0.0"
description = "Semantic Versioning in Ada"
licenses = ["LGPL 3.0"]

authors = [ "Alejandro R. Mosteo" ]
maintainers = [ "alejandro@mosteo.com", ]
maintainers-logins = [ "mosteo", ]

tags = ["semver", "semantic", "versioning"]
