name = "semantic_versioning"
version = "2.1"
description = "Semantic Versioning in Ada"
licenses = "LGPL-3.0-only"
website = "https://github.com/alire-project/semantic_versioning"

authors = [ "Alejandro R. Mosteo" ]
maintainers = [ "alejandro@mosteo.com", ]
maintainers-logins = [ "mosteo", ]

tags = ["semver", "semantic", "versioning"]
