name: build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '*.md'

jobs:

  build:
    name: ${{ matrix.os }} / GNAT ${{ matrix.gnat }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macos-12
          - ubuntu-latest
          - windows-latest
        gnat: [10, 11, 12, 13, 14]

    steps:
    - name: Check out repository
      uses: actions/checkout@v1

    - name: Check out submodules
      run: git submodule update --init --recursive

    - name: Set up GNAT toolchain (FSF)
      uses: alire-project/alr-install@v1
      with:
        crates: gnat_native^${{matrix.gnat}} gprbuild

    - name: Build on demand
      run: gprbuild -j0 -p -XSEMVER_BUILD_MODE=On_Demand

    - name: Build static lib
      run: gprbuild -j0 -p -XSEMVER_BUILD_MODE=Static_Lib

    - name: Build shared lib
      run: gprbuild -j0 -p -XSEMVER_BUILD_MODE=Shared_Lib

    - name: Set up nightly Alire to run testsuite
      uses: alire-project/setup-alire@v4
      with:
        version: nightly

    - name: Run tests
      run: alr test
