name: build

on:
  push:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - '*.md'

jobs:

  build:
    name: ${{ matrix.os }}
 
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
 
    steps:
    - name: Check out repository
      uses: actions/checkout@v1

    - name: Check out submodules
      run: git submodule update --init --recursive

    - name: Set up GNAT toolchain (FSF)
      if: matrix.os == 'ubuntu-latest'
      uses: ada-actions/toolchain@ce2021
      with:
        distrib: fsf 

    - name: Set up GNAT toolchain (Community 2021)
      if: matrix.os == 'windows-latest'
      uses: ada-actions/toolchain@ce2021
      with:
        distrib: community

    - name: Set up GNAT toolchain (Community 2020)
      if: matrix.os == 'macos-latest'
      uses: ada-actions/toolchain@ce2020
      with:
        distrib: community

    - name: Build on demand
      run: gprbuild -j0 -p -XSEMVER_BUILD_MODE=On_Demand

    - name: Build static lib
      run: gprbuild -j0 -p -XSEMVER_BUILD_MODE=Static_Lib

    - name: Build shared lib
      run: gprbuild -j0 -p -XSEMVER_BUILD_MODE=Shared_Lib

    - name: Run test programs
      run: bin/demo
